default: &default
  adapter: postgresql
  encoding: UTF8
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_development
  port: 5432

test:
  <<: *default
  database: Blog_test
  port: 5432

production:
  <<: *default
  database: Blog_hotwire_production
  username: Blog_hotwire
  password: <%= ENV["BLOG_HOTWIRE_DATABASE_PASSWORD"] %>
